"""Decision Intelligence — per-domain drill-down: metrics, insights, root causes,
risks, opportunities, a prioritised recommendation matrix, and a scorecard."""
from __future__ import annotations

import pandas as pd
import plotly.express as px
import streamlit as st

from app import components as C
from app import data, theme


def _recommendation_matrix(recs, currency, fy):
    """2×2 impact-vs-effort scatter of recommendations (matches the .docx matrix)."""
    if not recs:
        return
    lev = {"high": 3, "medium": 2, "low": 1}
    df = pd.DataFrame([{
        "text": r.text,
        "impact": lev.get(r.impact, 2),
        "effort": lev.get(r.effort, 2),
        "priority": r.priority_score,
        "confidence": r.confidence,
    } for r in recs])
    fig = px.scatter(
        df, x="effort", y="impact", size="priority", color="priority",
        color_continuous_scale=["#B11B1B", "#B06A00", "#1E7E34"],
        hover_name="text", size_max=34,
    )
    fig.update_xaxes(tickvals=[1, 2, 3], ticktext=["Low", "Medium", "High"], title="Effort")
    fig.update_yaxes(tickvals=[1, 2, 3], ticktext=["Low", "Medium", "High"], title="Impact")
    fig.update_layout(height=360, margin=dict(l=10, r=10, t=10, b=10))
    st.plotly_chart(fig, width="stretch")


def render(opts: dict) -> None:
    currency, profile, fy = opts["currency"], opts["profile"], opts["fy"]

    st.markdown("## Decision Intelligence")
    st.caption("Each business domain explained: what is happening, why, the risks, "
               "and the recommended actions — generated by the DI engine.")

    if not data.warehouse_exists():
        st.warning("Build the warehouse first (`python run_pipeline.py`).")
        return

    reports = data.domain_reports()
    domains = [r.domain for r in reports]
    labels = {r.domain: r.domain.replace("_", " ").title() for r in reports}

    domain = st.selectbox("Domain", domains, format_func=lambda d: labels[d])
    rep = data.domain_report(domain)
    if rep is None:
        st.error("Domain not found.")
        return

    # Scorecard headline
    head = st.columns([3, 1])
    with head[0]:
        st.markdown(f"### {labels[domain]}")
    with head[1]:
        if rep.scorecard:
            C.grade_badge(rep.scorecard.grade, rep.scorecard.score)

    # ── KPI cards ───────────────────────────────────────────────────────────
    if rep.metrics:
        C.section("Key metrics")
        C.kpi_row(rep.metrics, currency, fy, per_row=4)

    # ── Narrative ───────────────────────────────────────────────────────────
    if rep.executive_summary:
        C.narrative_box(rep.executive_summary, title="Executive summary",
                        context=f"{labels[domain]} domain")

    # ── Insights / root causes ──────────────────────────────────────────────
    c1, c2 = st.columns(2)
    with c1:
        C.section("Insights")
        for ins in rep.insights:
            st.markdown(f"{theme.badge(ins.severity, ins.severity)} {ins.text}",
                        unsafe_allow_html=True)
        if not rep.insights:
            st.caption("No notable insights this period.")
    with c2:
        C.section("Root causes")
        for rc in rep.root_causes:
            st.markdown(f"- {rc}")
        if not rep.root_causes:
            st.caption("—")

    # ── Risks & opportunities ───────────────────────────────────────────────
    c3, c4 = st.columns(2)
    with c3:
        C.section("Risks")
        for rk in sorted(rep.risks, key=lambda x: x.score, reverse=True):
            st.markdown(
                f"{theme.badge(f'{rk.score:.0f}', rk.severity)} **{rk.name}** — {rk.description}",
                unsafe_allow_html=True)
        if not rep.risks:
            st.caption("No material risks.")
    with c4:
        C.section("Opportunities")
        for op in sorted(rep.opportunities, key=lambda x: (x.potential_impact_inr or 0), reverse=True):
            impact = data.money(op.potential_impact_inr, currency, fy) if op.potential_impact_inr else ""
            conf = f" · {op.confidence:.0%} conf." if op.confidence else ""
            tag = f" ({impact}{conf})" if impact or conf else ""
            st.markdown(f"{theme.badge('opp', 'positive')} **{op.name}**{tag} — {op.description}",
                        unsafe_allow_html=True)
        if not rep.opportunities:
            st.caption("—")

    # ── Recommendations (table + matrix) ────────────────────────────────────
    if rep.recommendations:
        C.section("Recommendations", "Ranked by priority (impact × confidence ÷ effort).")
        recs = sorted(rep.recommendations, key=lambda r: r.priority_score, reverse=True)
        left, right = st.columns([1.3, 1])
        with left:
            df = pd.DataFrame([{
                "Priority": r.priority_score, "Recommendation": r.text,
                "Impact": r.impact, "Effort": r.effort, "Confidence": f"{r.confidence:.0%}",
            } for r in recs])
            st.dataframe(df, width="stretch", hide_index=True)
            C.download_df(df, f"recommendations_{domain}.csv", "⬇ Download recommendations (CSV)")
        with right:
            _recommendation_matrix(recs, currency, fy)
